import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, CheckCircle2, Database, Layers3, Workflow } from "lucide-react";
import { TopNav } from "@/components/network/TopNav";
import Footer from "@/components/standex-ai/Footer";

export const metadata: Metadata = {
  title: "Business Intelligence Solutions | Standex Digital",
  description: "Complete business intelligence systems built with Power Apps, Power Automate and Power BI—from data analysis and implementation to adoption.",
};

const solutions = [
  { icon: Layers3, title: "Power Apps", label: "Capture & operate", text: "Purpose-built business applications that replace fragmented forms, spreadsheets and manual processes with structured, usable data.", href: "/solutions/power-apps", colour: "text-fuchsia-600", surface: "bg-fuchsia-50" },
  { icon: Workflow, title: "Power Automate", label: "Connect & automate", text: "Reliable workflows that move information between teams and systems, trigger approvals and remove repetitive administration.", href: "/solutions/power-automate", colour: "text-blue-600", surface: "bg-blue-50" },
  { icon: BarChart3, title: "Power BI", label: "Analyse & decide", text: "Trusted data models, dashboards and reporting that give leaders and teams a shared view of business performance.", href: "/solutions/power-bi", colour: "text-amber-600", surface: "bg-amber-50" },
];

const delivery = [
  ["Discover", "Define the decisions, users, workflows and source data the BI system must support."],
  ["Analyse", "Profile the data, resolve quality issues and design a dependable reporting model."],
  ["Implement", "Build the Power Apps, automated workflows, semantic models and Power BI experience."],
  ["Embed", "Test with real users, document governance and support adoption across the organisation."],
];

export default function BISolutionsPage() {
  return <div className="min-h-screen bg-white text-zinc-950"><TopNav /><main className="overflow-x-hidden">
    <section className="relative overflow-hidden bg-zinc-950 px-4 pb-24 pt-36 text-white sm:px-6 sm:pt-40 lg:px-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(124,92,252,.22),transparent_34%),radial-gradient(circle_at_15%_80%,rgba(242,200,17,.12),transparent_35%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-white">Business Intelligence Solutions</p><h1 className="mt-6 text-5xl font-bold leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">Build a complete BI system around how your business works.</h1><p className="mt-7 max-w-2xl text-lg font-medium leading-relaxed text-white sm:text-xl">We combine Power Apps, Power Automate and Power BI to capture better data, improve processes and turn information into decisions.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link href="/Contact" className="inline-flex min-h-14 items-center justify-center gap-3 rounded-2xl bg-violet-600 px-7 text-sm font-bold text-white hover:bg-violet-700">Discuss a BI Solution <ArrowRight className="h-4 w-4" /></Link><Link href="#bi-solutions" className="inline-flex min-h-14 items-center justify-center rounded-2xl border border-white/25 px-7 text-sm font-bold text-white hover:bg-white/10">Explore the system</Link></div></div><div className="relative aspect-[4/3] overflow-hidden rounded-[32px] border border-white/10"><Image src="/DataIntelligenceLarge.webp" alt="Business intelligence dashboards and data analysis" fill priority sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-zinc-950/60 via-transparent to-transparent" /></div></div></section>

    <section id="bi-solutions" className="scroll-mt-24 px-4 py-20 sm:px-6 sm:py-28 lg:px-12"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-violet-700">One connected Microsoft system</p><h2 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Capture. Automate. Analyse.</h2><p className="mt-5 text-lg font-medium leading-relaxed text-zinc-700">Each product solves a distinct part of the information journey. Together, they create a practical business intelligence system from frontline input to leadership reporting.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{solutions.map(({ icon: Icon, title, label, text, href, colour, surface }) => <Link key={title} href={href} className="group rounded-[30px] border border-zinc-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className={`flex h-14 w-14 items-center justify-center rounded-2xl ${surface} ${colour}`}><Icon className="h-7 w-7" /></div><p className={`mt-8 text-xs font-bold uppercase tracking-[.22em] ${colour}`}>{label}</p><h3 className="mt-3 text-3xl font-bold">{title}</h3><p className="mt-4 font-medium leading-relaxed text-zinc-700">{text}</p><span className={`mt-8 inline-flex items-center gap-2 text-sm font-bold ${colour}`}>Explore {title} <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></div></section>

    <section className="bg-zinc-950 px-4 py-20 text-white sm:px-6 sm:py-28 lg:px-12"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><Database className="h-8 w-8 text-white" /><p className="mt-8 text-xs font-bold uppercase tracking-[.25em] text-white">Data analysis & implementation</p><h2 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">From scattered data to a system people can use.</h2><p className="mt-6 font-medium leading-relaxed text-white">We do the analysis and implementation work around the Microsoft tools: source assessment, modelling, integration, dashboard design and user adoption.</p></div><ol className="grid gap-px overflow-hidden rounded-[28px] border border-zinc-800 bg-zinc-800 sm:grid-cols-2">{delivery.map(([title, text], index) => <li key={title} className="bg-zinc-950 p-7"><span className="text-xs font-bold text-white">0{index + 1}</span><h3 className="mt-6 text-xl font-bold text-white">{title}</h3><p className="mt-3 text-sm font-medium leading-relaxed text-white">{text}</p></li>)}</ol></div></div></section>

    <section className="px-4 py-20 sm:px-6 sm:py-28 lg:px-12"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div className="relative aspect-[16/10] overflow-hidden rounded-[32px]"><Image src="/HomeAboutPic.webp" alt="Business analyst reviewing performance information" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /></div><div><p className="text-xs font-bold uppercase tracking-[.25em] text-violet-700">A complete BI foundation</p><h2 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Designed around decisions—not dashboards alone.</h2><div className="mt-7 space-y-4">{["Data captured consistently at the source", "Processes connected through dependable automation", "Shared definitions and trusted reporting models", "Role-specific dashboards that lead to action", "Implementation support from discovery through adoption"].map(item => <p key={item} className="flex gap-3 font-semibold text-zinc-700"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-violet-600" />{item}</p>)}</div><Link href="/Contact" className="mt-9 inline-flex items-center gap-2 rounded-2xl bg-zinc-950 px-7 py-4 text-sm font-bold text-white">Plan your BI system <ArrowRight className="h-4 w-4" /></Link></div></div></section>

    <section className="bg-violet-600 px-4 py-16 text-white sm:px-6 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-white">Power Apps + Power Automate + Power BI</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Build one connected system for data and decisions.</h2></div><Link href="/Contact" className="inline-flex min-h-14 items-center gap-3 rounded-2xl bg-zinc-950 px-7 text-sm font-bold text-white">Discuss your requirements <ArrowRight className="h-4 w-4" /></Link></div></section>
  </main><Footer /></div>;
}
