export const digitalGrowthServices = [
  {
    slug: "google-ads",
    title: "Google Ads",
    shortTitle: "Paid Search",
    eyebrow: "High-intent acquisition",
    description: "Turn active search demand into qualified opportunities with tightly managed campaigns, landing pages and spend.",
    promise: "Capture demand without losing control of the budget.",
    intro: "We manage Google Ads as a commercial system—not a collection of keywords. Account structure, intent, creative, landing pages and measurement are managed together so investment follows evidence.",
    outcomes: ["Sharper campaign and keyword structure", "Clear budget allocation by commercial priority", "Ongoing ad and landing-page testing", "Transparent lead quality and cost reporting"],
    deliverables: ["Account and conversion audit", "Search and Performance Max strategy", "Campaign build or restructure", "Ad copy and asset testing", "Negative-keyword and search-term management", "Monthly performance and budget review"],
    icon: "target",
  },
  {
    slug: "analytics",
    title: "Analytics & Measurement",
    shortTitle: "Analytics",
    eyebrow: "Decisions you can trust",
    description: "Build a reliable measurement layer across GA4, advertising platforms, conversions and commercial reporting.",
    promise: "Know what is working, what is not and what to do next.",
    intro: "Growth becomes manageable when the numbers are dependable. We design practical measurement around the decisions your team needs to make, connecting acquisition activity to meaningful business outcomes.",
    outcomes: ["Reliable conversion and event tracking", "A shared view of channel performance", "Less time reconciling conflicting reports", "Faster budget and campaign decisions"],
    deliverables: ["GA4 and tag implementation audit", "Conversion and event architecture", "Google Tag Manager configuration", "Cross-channel dashboard design", "Attribution and data-quality review", "Monthly insight and action reporting"],
    icon: "chart",
  },
  {
    slug: "social-media-ads",
    title: "Social Media Advertising",
    shortTitle: "Social Ads",
    eyebrow: "Create and convert demand",
    description: "Reach the right audiences with disciplined paid social campaigns, useful creative testing and measurable funnels.",
    promise: "Build demand with creative that earns attention and campaigns that learn.",
    intro: "Paid social works when audience, offer, creative and follow-up operate as one journey. We plan and manage that journey across the platforms that fit your market rather than spreading budget everywhere.",
    outcomes: ["A clearer audience and offer strategy", "Structured creative experimentation", "Better alignment between ads and landing pages", "Meaningful reporting beyond clicks and impressions"],
    deliverables: ["Channel and audience strategy", "Meta and LinkedIn campaign management", "Creative concepts and test plans", "Retargeting and funnel design", "Pixel and conversion validation", "Performance and learning reviews"],
    icon: "megaphone",
  },
  {
    slug: "email-marketing",
    title: "Email Marketing & Automation",
    shortTitle: "Email",
    eyebrow: "Nurture demand into action",
    description: "Create lifecycle email journeys that follow up leads, deepen customer relationships and support repeatable growth.",
    promise: "Make every new lead and customer relationship work harder.",
    intro: "Email should be more than occasional broadcasts. We create purposeful journeys around real customer moments—from first enquiry and education to conversion, onboarding and re-engagement.",
    outcomes: ["Consistent follow-up without manual effort", "More relevant communication by audience stage", "A stronger path from lead to opportunity", "Clear visibility into engagement and conversion"],
    deliverables: ["Lifecycle and database audit", "Segmentation and journey mapping", "Nurture and conversion sequences", "Campaign calendars and templates", "Automation implementation", "Deliverability and performance optimisation"],
    icon: "mail",
  },
  {
    slug: "seo-content",
    title: "SEO & Content Growth",
    shortTitle: "SEO & Content",
    eyebrow: "Compound organic visibility",
    description: "Build useful search visibility around customer demand, commercial priorities and content your market values.",
    promise: "Become easier to find—and more useful when prospects arrive.",
    intro: "We combine technical SEO, search intent and subject expertise into a practical content programme. The goal is not traffic for its own sake, but sustained visibility with the people most likely to buy.",
    outcomes: ["Clear organic-search priorities", "Stronger technical foundations", "Content mapped to customer intent", "A repeatable publishing and improvement rhythm"],
    deliverables: ["Technical and content audit", "Keyword and opportunity mapping", "Content strategy and briefs", "On-page and internal-link optimisation", "Authority and distribution planning", "Search performance reporting"],
    icon: "search",
  },
] as const;

export type DigitalGrowthService = (typeof digitalGrowthServices)[number];
